### ISSUE TITLE
[Suggestion] Adding an item for monthly shop reset

### ISSUE THREAD

**Issue by starg09** [cori2cori/Kamihama-Clock-Tower#3]
Doing an issue instead of a PR since there's two potential approaches to this, if considered:

1. Adding an entry as all others, with an expire date for next month, and just update it each month over and over
2. Have a type of entry that gets a day number, an hour, and it automatically renews based on current month for stuff like this.

Would you consider adding the monthly shop reset, in one of these ways? Even if relatively simple to plan for, it'd probably be appreciated for many players as a reminder :)

**Comment by jmcruzblazquez** [comment]
Now the shop event group automatically adds a "Monthly Magia Stones Shops" timer. 

Thanks for the suggestion.
